apiVersion: v1
kind: Service
metadata:
  name: {{ include "argusai.backendFullname" . }}
  labels:
    {{- include "argusai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "argusai.backendSelectorLabels" . | nindent 4 }}
